name: Warmer
on:
  push:
    branches: 
      - master
  schedule:
    - cron: '*/30 * * * *'
jobs:
  warmer:
    runs-on: ubuntu-latest
    steps:
      - name: branch checkout
        uses: actions/checkout@v2
      - run: npm install && node ./init.js https://google.com && ls -alh
